初回UP
sasshun/For-Training_s.sato pull request #1
Opened 2022-12-18 23:56 UTC by sasshun

エンジスキルマップ必修課題「HTTPの基礎」のコードです。

2022-12-22 02:40 UTC, as-fujita commented
@sasshun コメントしたのでご確認をお願いします！

2022-12-22 04:25 UTC, as-fujita requested changes

2022-12-22 04:25 UTC, as-fujita commented on task1-http/get/index.html
> +    </form>
# Nits
インデント気にしましょう～
```suggestion
    <form method="get" action="receive.php">
        ポケモン：<input type="text" name="pokemon">
        <input type="submit" value="送信">
    </form>
```

2022-12-22 04:25 UTC, as-fujita commented on task1-http/post/index.html
> +    </form>
# Nits
インデント気にしましょう～
```suggestion
    <form method="post" action="receive.php">
        ポケモン：
        <select name="category">
            <option value="">選択してください</option>
            <option value="1">ホゲータ</option>
            <option value="2">クワッス</option>
            <option value="3">ニャオハ</option>
        </select>
        <input type="submit" value="送信">
    </form>
```

2022-12-22 04:49 UTC, sasshun commented on task1-http/post/receive.php
> +if ($_POST['category'] === '3') echo "ニャオハ";
https://designsupply-web.com/media/programming/5563/
case文かelse if文があると思いました！
else if文で修正します！
この書き方にした理由はコピペで数字と文字列のところを書き換えれば早くかけると思ったからです！

2022-12-22 04:59 UTC, sasshun commented on task1-http/cookie/example1.php
> +setcookie($key, $message, $expires);
https://gray-code.com/php/setting-timezone/
こちらですね！

2022-12-22 09:48 UTC, sasshun commented
あ、間違えたかもしれない、、。
再提出するときはどうすればいいですか？
調べます。

2022-12-23 00:19 UTC, sasshun commented
修正版をプッシュしました！

2023-01-06 05:18 UTC, merged