apache課題一次提出
sasshun/For-Training_s.sato pull request #6
Opened 2023-02-07 10:06 UTC by sasshun

### 概要
apache課題
vhosts、環境変数、mod_rewrite (htaccess)、アドレスとポートのバインド、BASIC認証／アクセス制限、ログファイル
の一次提出です。

### 現状
**詳細についてはディレクトリ構造など前提情報.txtに記載しています。**
環境変数課題の「教育担当者の指示を仰ぎ、上記スクリプトを本番サーバにリリースしてください。また、本番サーバのApacheではTEST_ENVの値としてPRODUCTIONを設定し、ブラウザ上に「本番環境です」と表示されることを確認してください。」だけまだ完了していません。

AWSの設定の何処かがおかしく、index.phpの挙動が理想と異なります。
具体的には「phpのコードが文字として認識され、ブラウザ画面上に標示されてしまう」ことがあります。
ローカル環境ではこのような問題はなかったので、AWSに問題があると考えています。

2023-02-08 02:39 UTC, as-fujita requested changes

2023-02-08 02:39 UTC, as-fujita commented on task4/ディレクトリ構造など前提情報.txt
> +    ＊リダイレクトの方ではURLパラメータの概要とPHPでURLパラメータを受け取る方法を学びました(getenv)。
# Nits
`getenv()`はURLパラメータじゃなく環境変数を取得する関数ですね…！

2023-02-08 02:39 UTC, as-fujita commented on task4/ディレクトリ構造など前提情報.txt
> +    ＊RequireRuleで正規表現を書く際、URLのドメイン直後の「/」がパターンに含まれる場合とそうでない場合があるとの記事を読み、こんがらがりそうでした。
```suggestion
    ＊RewriteRuleで正規表現を書く際、URLのドメイン直後の「/」がパターンに含まれる場合とそうでない場合があるとの記事を読み、こんがらがりそうでした。
```

実案件では、実際に試して調整するのが確実ですね

2023-02-08 02:39 UTC, as-fujita commented on task4/vhosts/test4/.htaccess
> +#RewriteRule ^index\.php$ http://example.local/ [R=301,L]
# SHOULD
サイトのドメインを決め打ちしない書き方にしてほしいです！

たとえば `one.example.com` がテスト環境だとして、ここと別のディレクトリに共通のコードを置いたときも動くように、汎用的な書き方にしたいです！

`http://one.example.com/index.php` にアクセスされたら `http://one.example.com/` に301リダイレクト
かつ
`http://example.local/index.php` にアクセスされたら `http://example.local/` に301リダイレクト

2023-02-08 02:39 UTC, as-fujita commented on task4/vhosts/test4/admin/.htaccess
> +AuthUserFile "/var/www/vhosts/.htpasswd"
# SHOULD
ドキュメントルート外に配置したのはナイスです！
実案件だと、Basic認証をかけたいディレクトリに配置した .htaccess に記載して、同じ階層に.htpasswdも置くことが多いかな。
場所がわかりやすい（探す手間、アップロードできているか確認しやすい）のと、↑の絶対パスと同じディレクトリ構成じゃない場合でも、共通で使えて便利なため。

パーミッション大事なので、どう設定したかはテキストファイルに記載してほしいです！

2023-02-08 02:39 UTC, as-fujita commented on task4/vhosts/test4/.htaccess
> +RewriteRule ^123/$ /index\.php?q=123 [L]
# IMO
`/124/` にアクセスされたら `/index.php?q=124` 、125, 126, ... も同様に、というように他の数字でもリライトするような書き方にしてみましょう！

2023-02-08 02:39 UTC, as-fujita commented on task4/ディレクトリ構造など前提情報.txt
> +    RewriteCondディレクティブを用いて条件分岐することはわかったのですが、まだ自分で設定できるところまで理解できていません。
# Comment
今は「すべての `/` で終わるアドレスのとき」リダイレクトの分岐に入るようになっているけど、
リダイレクト`/123/` リライトの分岐に入れるときは、リダイレクトの分岐に入らないように設定したいですね！

2023-02-08 02:39 UTC, as-fujita commented on task4/ディレクトリ構造など前提情報.txt
> +    ＊ポートを書く場所はドメインのすぐ後ろだということを学びました。URLの一番最後にポートを記載していてエラーになってしまう事がありました。
👌

2023-02-08 02:39 UTC, as-fujita commented on task4/engclub.conf
> +    </Directory>
# Nits
インデント

2023-02-08 05:29 UTC, sasshun commented on task4/vhosts/test4/admin/.htaccess
> +AuthUserFile "/var/www/vhosts/.htpasswd"
取り急ぎ共有メモ
`-rw-r--r--. 1 root root 21 Feb  3 06:18 .htpasswd`

2023-02-08 06:11 UTC, sasshun commented on task4/vhosts/test4/.htaccess
> +RewriteRule ^123/$ /index\.php?q=123 [L]
[https://lpeg.info/html/htaccess_redirect.html](https://lpeg.info/html/htaccess_redirect.html)
こちらの記事を参考に`RewriteRule ^(.*)/$ /index\.php?q=$1 [L]`
と記載したところ他の数字でもリライトできました。

ただ`/123/`ではなく`/123`とした入力した時Not Foundとなってしまいます。最後のスラッシュを書かなかった場合でも同様のリライトをするように設定したいのですが、ここについてはわかりませんでした。

2023-02-08 06:13 UTC, sasshun commented on task4/engclub.conf
> +    </Directory>
😿

2023-02-08 06:16 UTC, sasshun commented on task4/ディレクトリ構造など前提情報.txt
> +    ＊リダイレクトの方ではURLパラメータの概要とPHPでURLパラメータを受け取る方法を学びました(getenv)。
😿

2023-02-08 07:49 UTC, sasshun commented on task4/ディレクトリ構造など前提情報.txt
> +    RewriteCondディレクティブを用いて条件分岐することはわかったのですが、まだ自分で設定できるところまで理解できていません。
### Question
こちら考え方としては
`index.php/`で終わる時は`example.com`にリダイレクトさせ、
それ以外の時はリライトさせる
という分岐をRewriteCondで実装する。
であっていますか？

2023-02-08 08:12 UTC, ShunichiBaba commented on task4/ディレクトリ構造など前提情報.txt
> +    RewriteCondディレクティブを用いて条件分岐することはわかったのですが、まだ自分で設定できるところまで理解できていません。
`/123/`のときはリダイレクトしないようにするって表現のほうが正しい気がする～

2023-02-08 08:16 UTC, as-fujita commented on task4/vhosts/test4/.htaccess
> +RewriteRule ^123/$ /index\.php?q=123 [L]
この場合、実案件の話をすると `/123` へのアクセスを `/123/` にリダイレクトするのが一般的ですね。
どのページにアクセスされたかをGoogle Analyticsで分析するために、URLを統一したい要望が考えられるため。

正規表現だけの話をすると、
`^(.*)/$` これは末尾が必ず「/」になっていることが条件になっているので、そこを「/」または何もない場合と表現できると良いですね～

あと、 `.*` だとあらゆる0文字以上の文字列になっちゃうので、「他の数字」だけ該当するようにしましょう！

2023-02-08 08:17 UTC, as-fujita commented on task4/vhosts/test4/.htaccess
> +RewriteRule ^123/$ /index\.php?q=123 [L]
この場合、実案件の話をすると `/123` へのアクセスを `/123/` にリダイレクトするのが一般的ですね。
どのページにアクセスされたかをGoogle Analyticsで分析するために、URLを統一したい要望が考えられるため。

正規表現だけの話をすると、
`^(.*)/$` これは末尾が必ず「/」になっていることが条件になっているので、そこを「/」または何もない場合と表現できると良いですね～

あと、 `.*` だとあらゆる0文字以上の文字列になっちゃうので、「他の数字」だけ該当するようにしましょう！

2023-02-08 09:20 UTC, sasshun commented on task4/vhosts/test4/.htaccess
> +RewriteRule ^123/$ /index\.php?q=123 [L]
```
正規表現だけの話をすると、
^(.*)/$ これは末尾が必ず「/」になっていることが条件になっているので、そこを「/」または何もない場合と表現できると良いですね～
```
ここは解決
`RewriteRule ^([0-9]*)/*$ /index\.php?q=$1 [L]`

2023-02-09 01:05 UTC, as-fujita commented on task4/vhosts/test4/.htaccess
> +RewriteRule ^123/$ /index\.php?q=123 [L]
新しくコメントしました！

細かいところですが文体のFB：引用のときはコードブロックじゃなくて「>」を文頭につけましょう～

>「文中に出現するスラッシュの有無に関わらず、末尾にスラッシュがない場合」

具体的な表現から始めて一般化するとよいです！

`/123` へのアクセスを `/123/` にリダイレクト
→`/(123)` (123を変数化)へのアクセスを `/(変数)/` にリダイレクト
→`/[数字]` へのアクセスを `/(変数)/` にリダイレクト

ヒント：末尾の表現は「$」。`*` はマッチする文字列が多くなって複雑になります。今回は `*` なしでいけます…！

2023-02-09 02:44 UTC, sasshun commented on task4/vhosts/test4/.htaccess
> +#RewriteRule ^index\.php$ http://example.local/ [R=301,L]
`http://one.example.com/`の部分は.confファイルのServerNameで設定するしか無いと思っています。
RewriteRuleでURL全てを正規表現の参照対象にする方法をまだ理解していません。

2023-02-14 02:31 UTC, merged